"""
Reporter module for generating markdown reports from analyzed releases.
"""

import logging
from datetime import datetime, timezone
from typing import List, Dict

logger = logging.getLogger(__name__)


class MarkdownReporter:
    """Generates markdown reports from analyzed release data."""

    SEVERITY_EMOJI = {
        "critical": "🔴",
        "high": "🟠",
        "medium": "🟡",
        "low": "🔵",
        "info": "⚪",
    }

    def generate(self, analyzed_releases: List[Dict], stats: Dict) -> str:
        """Generate a full markdown report."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

        lines = []
        lines.append(f"# Kubernetes Ecosystem Release Report")
        lines.append(f"**Generated:** {now}")
        lines.append("")

        # Summary section
        lines.append(self._generate_summary(stats))

        # Breaking changes section (high priority)
        breaking = [r for r in analyzed_releases if r.get("has_breaking_changes")]
        if breaking:
            lines.append("---")
            lines.append("")
            lines.append("## Breaking Changes & Deprecations")
            lines.append("")
            for release in breaking:
                lines.append(self._format_breaking_release(release))
        else:
            lines.append("---")
            lines.append("")
            lines.append("## Breaking Changes & Deprecations")
            lines.append("")
            lines.append("No breaking changes detected in this period.")
            lines.append("")

        # All releases section
        non_breaking = [r for r in analyzed_releases if not r.get("has_breaking_changes")]
        if non_breaking:
            lines.append("---")
            lines.append("")
            lines.append("## Other Releases & Updates")
            lines.append("")
            for release in non_breaking:
                lines.append(self._format_release(release))

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*This report is auto-generated by [k8s-release-tracker](https://github.com/YOUR_USERNAME/k8s-release-tracker). "
                      "Breaking changes are detected via keyword matching and may include false positives.*")
        lines.append("")

        return "\n".join(lines)

    def _generate_summary(self, stats: Dict) -> str:
        """Generate the summary section."""
        lines = []
        lines.append("## Summary")
        lines.append("")
        lines.append(f"| Metric | Count |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Total releases/updates | {stats['total_releases']} |")
        lines.append(f"| Breaking changes | {stats['breaking_changes']} |")

        for severity in ["critical", "high", "medium", "low"]:
            count = stats["by_severity"].get(severity, 0)
            if count > 0:
                emoji = self.SEVERITY_EMOJI.get(severity, "")
                lines.append(f"| {emoji} {severity.capitalize()} severity | {count} |")

        lines.append("")

        # Per-source breakdown
        if stats.get("by_source"):
            lines.append("### By Source")
            lines.append("")
            lines.append("| Source | Total | Breaking |")
            lines.append("|--------|-------|----------|")
            for source, counts in sorted(stats["by_source"].items()):
                breaking_marker = f"**{counts['breaking']}**" if counts["breaking"] > 0 else "0"
                lines.append(f"| {source} | {counts['total']} | {breaking_marker} |")
            lines.append("")

        return "\n".join(lines)

    def _format_breaking_release(self, release: Dict) -> str:
        """Format a release with breaking changes."""
        lines = []
        severity = release.get("severity", "info")
        emoji = self.SEVERITY_EMOJI.get(severity, "")
        source = release.get("source", "Unknown")
        version = release.get("version", "")
        title = release.get("title", "Untitled")
        date = release.get("date", "")[:10]
        url = release.get("url", "")

        header = f"### {emoji} [{source}] {title}"
        if version:
            header += f" ({version})"
        lines.append(header)
        lines.append("")

        lines.append(f"- **Date:** {date}")
        lines.append(f"- **Severity:** {severity.capitalize()}")
        if url:
            lines.append(f"- **Link:** [{url}]({url})")

        # Show matched keywords
        keywords = release.get("matched_keywords", [])
        if keywords:
            lines.append(f"- **Matched keywords:** {', '.join(keywords)}")

        # Show breaking change sections
        sections = release.get("breaking_sections", [])
        if sections:
            lines.append("")
            lines.append("<details>")
            lines.append("<summary>Breaking change details (click to expand)</summary>")
            lines.append("")
            for section in sections:
                lines.append("```")
                lines.append(section[:500])
                lines.append("```")
            lines.append("")
            lines.append("</details>")

        lines.append("")
        return "\n".join(lines)

    def _format_release(self, release: Dict) -> str:
        """Format a regular (non-breaking) release."""
        source = release.get("source", "Unknown")
        version = release.get("version", "")
        title = release.get("title", "Untitled")
        date = release.get("date", "")[:10]
        url = release.get("url", "")

        header = f"- **[{source}]** {title}"
        if version:
            header += f" `{version}`"
        header += f" — {date}"
        if url:
            header += f" ([link]({url}))"

        return header + "\n"


def generate_report_filename() -> str:
    """Generate a filename for today's report."""
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return f"{date_str}-release-report.md"
